services:
  yourope:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yourope
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
    name: retro-tool_default
